### ISSUE TITLE
Not working for EA

### ISSUE THREAD

**Issue by Baarten** [lzeke0/TwitchRSS#11]
I added some feeds to [Feeder](https://gitlab.com/spacecowboy/Feeder) and TwitchRSS worked great! 

Then I tried adding EA with the following URL: https://twitchrss.appspot.com/vod/EA. 
Now Feeder couldn't find the feed. I also tried with "ea". 

I succesfully added another feed afterwards.

**Comment by lzeke0** [comment]
Yeah, Twitch had a rule that was modelled in the service code. Namely usernames have to have a minimum of 3 characters. I guess EA paid enough to make them create this username.

Anyway, this should be an easy fix.

**Comment by lzeke0** [comment]
This is fixed now.
