### ISSUE TITLE
Add VOD of current livestream to vodonly feed.

### ISSUE THREAD

**Issue by ghost** [lzeke0/TwitchRSS#12]
On Twitch you can watch VOD of current livestream, so i ask for this capability to vodonly feed too.

**Comment by wyattscarpenter** [comment]
I have to anti-request this, as downloading a currently-updating vod has in the past resulted in me having a partial download: say the streamer is one hour in. Then I download the VOD. I get the VOD downlaoded after 15 minutes, but the stream continues for two hours. Now I have a 1h15m version of a 3h vod, a terrible error!

If such troubles could be avoided, however, I would be fine with the suggestion.

**Comment by lzeke0** [comment]
As mentioned in the other issue, this is mainly twitch's fault. I implemented a workaround but it might be broken by twitch any time. In the meanwhile, enjoy.
