### ISSUE TITLE
Error 503 Over Quota

### ISSUE THREAD

**Issue by Scorp48** [lzeke0/TwitchRSS#13]
![Capture](https://user-images.githubusercontent.com/70067415/109318545-352f3300-784e-11eb-8727-8d3f9b584d2c.PNG)
Example: https://twitchrss.appspot.com/vod/twitch
It seems that there are problems with the limitation, yesterday it did not work, this morning it does, but now (4 hours later) it seems to fail again, I guess someone made too many requests and the error jumps.

**Comment by lzeke0** [comment]
Yeah, just checked the traffic and it seems that someone effectively DDOS'd the service so it runs out of GCloud quota in 6 hours.
Good news: it will reset tomorrow.
Bad news: the person who makes 15 requests per second to /vod/mr1random can do it again tomorrow. :(

BTW just for clarity that results are cached for 10 minutes by the service so it makes no sense to query more than once in 10 minutes.

**Comment by Scorp48** [comment]
> 
> 
> Yeah, just checked the traffic and it seems that someone effectively DDOS'd the service so it runs out of GCloud quota in 6 hours.
> Good news: it will reset tomorrow.
> Bad news: the person who makes 15 requests per second to /vod/mr1random can do it again tomorrow. :(
> 
> BTW just for clarity that results are cached for 10 minutes by the service so it makes no sense to query more than once in 10 minutes.

Thanks for the quick reply, I hope that guy gets tired and stops blocking the service, even if the results are cached for 10 minutes is not specified in the README.md it doesn't make sense for someone to make 15 requests per second.

Anyway, I thank you for your work and I hope you have a good day.

**Comment by lzeke0** [comment]
Your point about the README.md is fair. I'll push an update that mentions the caching. Thanks!
