### ISSUE TITLE
add support for new twitch helix API (app not working in the meantime)

### ISSUE THREAD

**Issue by madiele** [lzeke0/TwitchRSS#17]
Twitch broke the v5 API so the switch is needed

I already implemented support for it in [my own fork](https://github.com/madiele/TwitchToPodcastRSS) but since I also severely modified the logic and scope (changed some libraries and added/removed some features) I'll need some time to make a decent pull request, if you want me to make one let me know and I'll try to adapt the code and send one when I find some time for it

**Comment by tomasparks** [comment]
> Twitch broke the v5 API so the switch is needed
:(

**Comment by madiele** [comment]
> that's why my twitch vod downloader is not working.... :(

V5 is supported for another year or so, but they screwed with the API in the meantime by adding the need to be authenticated for every request, while before you could do some request with no authentication.

That's why lot's of stuff has been breaking everywhere

**Comment by lzeke0** [comment]
I wonder what made them do that since that information is publicly available on their website without any authentication whatsoever.

Anyway, pull requests are welcome however I wonder if it's better to just migrate to the new API anyway.

I won't be able to spend time with this for at least a week so, I guess we have to live with it for a while.

**Comment by madiele** [comment]
I did the pull request #20, check it out when you have time, some feature are missing but should at least do in the mean time

**Comment by christincooper** [comment]
@madiele Thank you very much for the pull request. 

@lzeke0 Hope you gain the time to implement this fix on the live site soon so we can have the base up and running.

**Comment by misaalami** [comment]
I looked through the code adjustments by @madiele and it looks solid, great job!

ETA on having it approved here and pushed to the [production site](https://twitchrss.appspot.com/)? @lzeke0

Feel free to give me a shout if I can be of help.
