### ISSUE TITLE
Feed does not validate

### ISSUE THREAD

**Issue by User123698745** [lzeke0/TwitchRSS#2]
Some RSS readers do not accept the generated feed (e.g. [Inoreader](https://www.inoreader.com)).

[FEED Validator Result Example](https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Ftwitchrss.appspot.com%2Fvod%2Friotgames)

Errors:
- guid must be a full URL, unless isPermaLink attribute is false ([Help](https://www.feedvalidator.org/docs/error/InvalidHttpGUID.html))
- pubDate must be an RFC-822 date-time ([Help](https://www.feedvalidator.org/docs/error/InvalidRFC2822Date.html))
- Undefined item element: ttl ([Help](https://www.feedvalidator.org/docs/error/UndefinedElement.html))

Warnings:
- Feeds should not be served with the "application/xhtml+xml" media type ([Help](https://www.feedvalidator.org/docs/warning/UnexpectedContentType.html))
- Missing atom:link with rel="self" ([Help](https://www.feedvalidator.org/docs/warning/MissingAtomSelfLink.html))

**Comment by lzeke0** [comment]
Hi! Thanks for the report. I'll see what I can do to fix these (well, at least the errors).

**Comment by lzeke0** [comment]
Did some changes and the feed now is evaluated compliant by the validator with only one warning remaining.

**Comment by User123698745** [comment]
Awesome, that went quick. Thank you :smile:
