### ISSUE TITLE
Links doesn't work anymore

### ISSUE THREAD

**Issue by darkarth00** [lzeke0/TwitchRSS#21]
Links doesn't work anymore

**Comment by dsdsdsdgg** [comment]
Same issue. Getting a 500 server error.

![image](https://user-images.githubusercontent.com/35578434/129625819-6db5868b-bcdf-4b56-864a-d6ee8b2f2ff2.png)

**Comment by iamPanka** [comment]
Hi, same here

**Comment by christincooper** [comment]
Same here. I think it is because the author has not implemented the new helix twitch API. Someone has already submitted a commit for it so hoping the author will update their tool over at: https://twitchrss.appspot.com

**Comment by dsdsdsdgg** [comment]
This issue seems to be resolved. Thank you so much.

**Comment by darkarth00** [comment]
> This issue seems to be resolved. Thank you so much.

Hm.. still doesn't work for me. I'm using "Smart RSS" on chrome.

**Comment by lzeke0** [comment]
Now it should more or less work. On a side note gcloud makes my life worse every year.

**Comment by dsdsdsdgg** [comment]
> > This issue seems to be resolved. Thank you so much.
> 
> Hm.. still doesn't work for me. I'm using "Smart RSS" on chrome.

Assuming I got the [correct one](https://chrome.google.com/webstore/detail/smart-rss/eggggihfcaabljfpjiiaohloefmgejic).
Working fine for me. 
![image](https://user-images.githubusercontent.com/35578434/133153466-38877c7b-2900-4586-97ba-c9020a16a4f9.png)

**Comment by darkarth00** [comment]
Yeah. Works now. Thanks.
