### ISSUE TITLE
active streams (subs-only?) included in vodonly

### ISSUE THREAD

**Issue by wyattscarpenter** [lzeke0/TwitchRSS#22]
Hello. Today I had the misfortune of trying to use this excellent project to download some vods, only to find that the streamer's active stream was counted as a vodonly, resulting in my downloading only a partial version of the vod of that stream (as, by the time I had finished downloading it, the stream was not yet finished! — this is the problem I reference in https://github.com/lzeke0/TwitchRSS/issues/12#issuecomment-903426595 ). I doubt you will be able to replicate the issue in time based on this link, but the "vod" in question is https://www.twitch.tv/videos/1156494693, which is also what is currently streaming at https://www.twitch.tv/j_blow; you can see it listed in https://twitchrss.appspot.com/vodonly/j_blow

I don't think I've noticed this issue before, so it may have something to do with this vod being only available to subscribers. Or perhaps this flaw was introduced with the new api change in 3e7419429223e8a44d88a3d0572ad9f1e64a6e3c and I've just been lucky since then. I do seem to remember verifying at one point that vodonly worked as expected, though not specifically with sub-only vods/streams.

**Comment by lzeke0** [comment]
Twitch does not state that a "video" is an ongoing stream in their API anymore. That being said they are also not sending a thumbnail when a stream is ongoing so I'm using that to detect if a stream is live now. The sad part is that it can be broken any time by twitch again. Anyway I'll close this in the meanwhile.
