### ISSUE TITLE
Doesn't seem to trigger on some live streams

### ISSUE THREAD

**Issue by diizzyy** [lzeke0/TwitchRSS#26]
Maybe I'm doing something wrong(tm) but it doesn't seem to trigger on live streams such as this one https://www.twitch.tv/onibabakoSushiTokyo ?

**Comment by lzeke0** [comment]
You are not doing anything wrong. The system works from past and ongoing VOD recordings but it seems that is turned off on this channel so they will not show up in the feed.

**Comment by diizzyy** [comment]
Ahh, I see bummer :/ Thanks for prompt reply! =)
