### ISSUE TITLE
VODs only feed.

### ISSUE THREAD

**Issue by lumiome** [lzeke0/TwitchRSS#4]
Can you do it please? Useless links to main channel are crapping rss aggregator and i have issues in commafeed with them not updating to VOD's link  after stream is finished.

**Comment by lzeke0** [comment]
That is quite easy to do. I can't promise anything concrete but I'll take a look soon.

**Comment by lzeke0** [comment]
Hey @lumiome , you can check it out here: https://twitchrss.appspot.com/vodonly/twitch or your favorite streamer.
